# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: 'windows-2019'

steps:
- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true

- task: PowerPlatformCreateEnvironment@0
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: 'Rpothin Trial'
    DisplayName: 'Production'
    EnvironmentSku: 'Trial'
    AppsTemplate: 'D365_Sales, D365_CustomerService, D365_FieldService, D365_ProjectServiceAutomation'
    LocationName: 'canada'
    LanguageName: '1033'
    CurrencyName: 'CAD'
    DomainName: 'crm3.dynamics.com'