# Pipeline used to delete a service endpoint

# Variables:
#   EnvironmentName - String - Not secret - Let user override
#   AzureDevOpsOrganizationURL - String - Secret - Do not let user override (ex: https://dev.azure.com/<organization>/)
#   PatToken - String - Secret - Do not let user override

# Pipeline triggered manually
trigger: none

pool:
  vmImage: 'windows-2019'

steps:
# Call to the pipeline template for the deletion of a Power Platform service endpoint
- template: ../Templates/delete-powerplatform-service-endpoint-template.yml