name: test
# Test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: windows-latest
    env:
      solution_name: PowerPlatformALMWithGitHub
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: Solutions/${{ env.solution_name }}
        solution-file: out/Solutions/${{ env.solution_name }}.zip
        solution-type: Unmanaged

    - name: Test
      run: ls
