name: test-powerplatform-environment

on:
  workflow_dispatch:

jobs:
  test-powerplatform-environment:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - name: Get modules
      shell: powershell
      run: |
        Install-Module -Name Microsoft.PowerApps.Administration.PowerShell -Force -Verbose -Scope CurrentUser
        Install-Module -Name Microsoft.PowerApps.PowerShell -AllowClobber -Force -Verbose -Scope CurrentUser
        Get-InstalledModule

    - name: Connect & Get locations
      shell: powershell
      run: |
        $pass = ConvertTo-SecureString "${{ secrets.user_password }}" -AsPlainText -Force
        Add-PowerAppsAccount -Username ${{ secrets.user_login }} -Password $pass

        Get-AdminPowerAppEnvironmentLocations