name: workspace-initialization-when-issue-assigned
# Create a branch and generate a Power Platform development environment when an issue is assigned

on:
  issues:
    types: [assigned]

env:
  ISSUE_DEV_BRANCH_NAME_BASE: Dev/issue_
  BRANCH_NAME: ${{ env.ISSUE_DEV_BRANCH_NAME_BASE }}${{ github.event.issue.number }}

jobs:
  create-issue-development-branch:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ env.BRANCH_NAME }}