name: workspace-initialization-when-issue-assigned
# Create a branch and generate a Power Apps development environment when an issue is assigned

on:
  issues:
    types: [assigned]

env:
  BRANCH_NAME: dev/issue_${{ github.event.issue.number }}
  POWERAPP_ENVIRONMENT_DISPLAY_NAME: Dev - Issue ${{ github.event.issue.number }}
  POWERAPP_ENVIRONMENT_LOCATION: canada
  POWERAPP_ENVIRONMENT_SKU: Trial
  POWERAPP_ENVIRONMENT_CURRENCY_NAME: CAD
  POWERAPP_ENVIRONMENT_LANGUAGE_CODE: 1033
  POWERAPP_ENVIRONMENT_DOMAIN_NAME: dev-issue-${{ github.event.issue.number }}

jobs:
  create-issue-development-branch:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ env.BRANCH_NAME }}

  create-powerapp-environment:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - name: Get PowerShell modules
      shell: powershell
      run: |
        Install-Module -Name Microsoft.PowerApps.Administration.PowerShell -Force -Verbose -Scope CurrentUser
        Install-Module -Name Microsoft.PowerApps.PowerShell -AllowClobber -Force -Verbose -Scope CurrentUser
    
    - name: Add Power Apps account
      shell: powershell
      run: |
        $pass = ConvertTo-SecureString "${{ secrets.DEV_USER_PASSWORD }}" -AsPlainText -Force
        Add-PowerAppsAccount -Username ${{ secrets.DEV_USER_LOGIN }} -Password $pass

    - name: Create Power Apps environment
      shell: powershell
      run: |
        New-AdminPowerAppEnvironment -DisplayName '${{ env.POWERAPP_ENVIRONMENT_DISPLAY_NAME }}' -Location ${{ env.POWERAPP_ENVIRONMENT_LOCATION }} -EnvironmentSku ${{ env.POWERAPP_ENVIRONMENT_SKU }} -ProvisionDatabase -CurrencyName ${{ env.POWERAPP_ENVIRONMENT_CURRENCY_NAME }} -LanguageName ${{ env.POWERAPP_ENVIRONMENT_LANGUAGE_CODE }} -DomainName '${{ env.POWERAPP_ENVIRONMENT_DOMAIN_NAME }}'