name: workspace-initialization-when-issue-assigned
# Create a branch and generate a Power Platform development environment when an issue is assigned

on:
  issues:
    types: [assigned]

jobs:
  create-issue-development-branch:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get issue number
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: echo "$ISSUE_NUMBER"
    #- uses: peterjgrainger/action-create-branch@v2.0.1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    branch: 'test'