name: workspace-initialization-when-issue-assigned
# Create a branch and generate a Power Apps development environment when an issue is assigned

on:
  issues:
    types: [assigned]

env:
  branch_name: dev/issue_${{ github.event.issue.number }}
  powerapps_environment_display_name: Dev - Issue ${{ github.event.issue.number }}
  powerapps_environment_domain_name: dev-issue-${{ github.event.issue.number }}
  powerapps_environment_url_base: .crm3.dynamics.com

jobs:
  create-issue-development-branch:
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ env.branch_name }}

  create-powerapps-dev-environment:
    runs-on: windows-latest
    env:
      powerapps_environment_location: canada
      powerapps_environment_sku: Trial
      powerapps_environment_currency_name: CAD
      powerapps_environment_language_code: 1033
      RUNNER_DEBUG: 1

    steps:
    - name: Get PowerShell modules
      shell: powershell
      run: |
        Install-Module -Name Microsoft.PowerApps.Administration.PowerShell -Force -Verbose -Scope CurrentUser
        Install-Module -Name Microsoft.PowerApps.PowerShell -AllowClobber -Force -Verbose -Scope CurrentUser
    
    - name: Add Power Apps account & Create Power Apps environment
      shell: powershell
      run: |
        $pass = ConvertTo-SecureString "${{ secrets.DEV_USER_PASSWORD }}" -AsPlainText -Force
        Add-PowerAppsAccount -Username ${{ secrets.DEV_USER_LOGIN }} -Password $pass
        
        New-AdminPowerAppEnvironment -DisplayName '${{ env.powerapps_environment_display_name }}' -Location ${{ env.powerapps_environment_location }} -EnvironmentSku ${{ env.powerapps_environment_sku }} -ProvisionDatabase -CurrencyName ${{ env.powerapps_environment_currency_name }} -LanguageName ${{ env.powerapps_environment_language_code }} -DomainName '${{ env.powerapps_environment_domain_name }}'

  # Enable this job only after the initialization of the solution in the repository
  #import-solution-to-dev-environment:
  #  needs: create-powerapps-dev-environment
  #  runs-on: windows-latest
  #  env:
  #    powerapps_environment_url_base: .crm3.dynamics.com
  #    solution_name: PowerPlatformALMWithGitHub
  #    RUNNER_DEBUG: 1

  #  steps:
  #  - uses: actions/checkout@v2
  #    with:
  #      lfs: true

  #  - name: Pack solution
  #    uses: microsoft/powerplatform-actions/pack-solution@v0
  #    with:
  #      solution-folder: Solutions/${{ env.solution_name }}
  #      solution-file: out/Solutions/${{ env.solution_name }}.zip
  #      solution-type: Unmanaged

  #  - name: Import solution as unmanaged to dev env
  #    uses: microsoft/powerplatform-actions/import-solution@v0
  #    with:
  #      environment-url: https://${{ env.powerapps_environment_domain_name }}${{ env.powerapps_environment_url_base }}
  #      user-name: ${{ secrets.DEV_USER_LOGIN }}
  #      password-secret: ${{ secrets.DEV_USER_PASSWORD }}
  #      solution-file: out/Solutions/${{ env.solution_name }}.zip
  #      force-overwrite: true
  #      publish-changes: true

  add-comment-on-issue:
    needs: [create-issue-development-branch, create-powerapps-dev-environment] #Change "create-powerapps-dev-environment" for "import-solution-to-dev-environment" only after the initialization of the solution in the repository
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - name: New comment on issue
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          # Workspace initialized!

          Branch: **${{ env.branch_name }}**
          Power Apps environment: [**${{ env.powerapps_environment_display_name }}**](https://${{ env.powerapps_environment_domain_name }}${{ env.powerapps_environment_url_base }})